# Generated by Django 4.2.5 on 2023-09-28 07:59

from django.db import migrations, models
import photoshare.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar.png', null=True, upload_to=photoshare.models.user_avatar_path),
        ),
    ]
