# Generated by Django 4.2.5 on 2023-10-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='topics',
        ),
        migrations.AddField(
            model_name='image',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photoshare.topic'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photoshare.tag'),
        ),
    ]
