# Generated by Django 4.2.5 on 2023-10-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoshare', '0004_rename_topic_image_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_path',
        ),
    ]
